// DirectInput keyboard scan code constants (from dinput.h)

export const DIK_ESCAPE = 1;
export const DIK_1 = 2;
export const DIK_2 = 3;
export const DIK_3 = 4;
export const DIK_4 = 5;
export const DIK_5 = 6;
export const DIK_6 = 7;
export const DIK_7 = 8;
export const DIK_8 = 9;
export const DIK_9 = 10;
export const DIK_0 = 11;
export const DIK_MINUS = 12;        // - on main keyboard
export const DIK_EQUALS = 13;
export const DIK_BACK = 14;         // backspace
export const DIK_TAB = 15;
export const DIK_Q = 16;
export const DIK_W = 17;
export const DIK_E = 18;
export const DIK_R = 19;
export const DIK_T = 20;
export const DIK_Y = 21;
export const DIK_U = 22;
export const DIK_I = 23;
export const DIK_O = 24;
export const DIK_P = 25;
export const DIK_LBRACKET = 26;
export const DIK_RBRACKET = 27;
export const DIK_RETURN = 28;       // Enter on main keyboard
export const DIK_LCONTROL = 29;
export const DIK_A = 30;
export const DIK_S = 31;
export const DIK_D = 32;
export const DIK_F = 33;
export const DIK_G = 34;
export const DIK_H = 35;
export const DIK_J = 36;
export const DIK_K = 37;
export const DIK_L = 38;
export const DIK_SEMICOLON = 39;
export const DIK_APOSTROPHE = 40;
export const DIK_GRAVE = 41;        // accent grave
export const DIK_LSHIFT = 42;
export const DIK_BACKSLASH = 43;
export const DIK_Z = 44;
export const DIK_X = 45;
export const DIK_C = 46;
export const DIK_V = 47;
export const DIK_B = 48;
export const DIK_N = 49;
export const DIK_M = 50;
export const DIK_COMMA = 51;
export const DIK_PERIOD = 52;       // . on main keyboard
export const DIK_SLASH = 53;        // / on main keyboard
export const DIK_RSHIFT = 54;
export const DIK_MULTIPLY = 55;     // * on numeric keypad
export const DIK_LMENU = 56;        // left Alt
export const DIK_SPACE = 57;
export const DIK_CAPITAL = 58;
export const DIK_F1 = 59;
export const DIK_F2 = 60;
export const DIK_F3 = 61;
export const DIK_F4 = 62;
export const DIK_F5 = 63;
export const DIK_F6 = 64;
export const DIK_F7 = 65;
export const DIK_F8 = 66;
export const DIK_F9 = 67;
export const DIK_F10 = 68;
export const DIK_NUMLOCK = 69;
export const DIK_SCROLL = 70;       // Scroll Lock
export const DIK_NUMPAD7 = 71;
export const DIK_NUMPAD8 = 72;
export const DIK_NUMPAD9 = 73;
export const DIK_SUBTRACT = 74;     // - on numeric keypad
export const DIK_NUMPAD4 = 75;
export const DIK_NUMPAD5 = 76;
export const DIK_NUMPAD6 = 77;
export const DIK_ADD = 78;          // + on numeric keypad
export const DIK_NUMPAD1 = 79;
export const DIK_NUMPAD2 = 80;
export const DIK_NUMPAD3 = 81;
export const DIK_NUMPAD0 = 82;
export const DIK_DECIMAL = 83;      // . on numeric keypad
export const DIK_F11 = 87;
export const DIK_F12 = 88;

export const DIK_NUMPADEQUALS = 141;    // = on numeric keypad (NEC PC98)
export const DIK_AT = 145;              // (NEC PC98)
export const DIK_COLON = 146;           // (NEC PC98)
export const DIK_UNDERLINE = 147;       // (NEC PC98)
export const DIK_STOP = 149;            // (NEC PC98)
export const DIK_AX = 150;              // (Japan AX)
export const DIK_UNLABELED = 151;       // (J3100)
export const DIK_NUMPADENTER = 156;     // Enter on numeric keypad
export const DIK_RCONTROL = 157;
export const DIK_NUMPADCOMMA = 179;     // , on numeric keypad (NEC PC98)
export const DIK_DIVIDE = 181;          // / on numeric keypad
export const DIK_SYSRQ = 183;
export const DIK_RMENU = 184;           // right Alt
export const DIK_HOME = 199;            // Home on arrow keypad
export const DIK_UP = 200;              // UpArrow on arrow keypad
export const DIK_PRIOR = 201;           // PgUp on arrow keypad
export const DIK_LEFT = 203;            // LeftArrow on arrow keypad
export const DIK_RIGHT = 205;           // RightArrow on arrow keypad
export const DIK_END = 207;             // End on arrow keypad
export const DIK_DOWN = 208;            // DownArrow on arrow keypad
export const DIK_NEXT = 209;            // PgDn on arrow keypad
export const DIK_INSERT = 210;          // Insert on arrow keypad
export const DIK_DELETE = 211;          // Delete on arrow keypad
export const DIK_LWIN = 219;            // Left Windows key
export const DIK_RWIN = 220;            // Right Windows key
export const DIK_APPS = 221;            // AppMenu key

// Aliases
export const DIK_BACKSPACE = DIK_BACK;
export const DIK_NUMPADSTAR = DIK_MULTIPLY;
export const DIK_LALT = DIK_LMENU;
export const DIK_CAPSLOCK = DIK_CAPITAL;
export const DIK_NUMPADMINUS = DIK_SUBTRACT;
export const DIK_NUMPADPLUS = DIK_ADD;
export const DIK_NUMPADPERIOD = DIK_DECIMAL;
export const DIK_NUMPADSLASH = DIK_DIVIDE;
export const DIK_RALT = DIK_RMENU;
export const DIK_UPARROW = DIK_UP;
export const DIK_PGUP = DIK_PRIOR;
export const DIK_LEFTARROW = DIK_LEFT;
export const DIK_RIGHTARROW = DIK_RIGHT;
export const DIK_DOWNARROW = DIK_DOWN;
export const DIK_PGDN = DIK_NEXT;
